language: java
jdk:
    - oraclejdk8
services:
    - postgresql
cache:
  directories:
    - $HOME/.m2
before_script:
    - psql -c 'create database wdaa;' -U postgres
    - psql -d 'wdaa' -c 'create schema wdaa;' -U postgres
    - mvn clean